name: Daily Script Runner

on:
  schedule:
    - cron: '30 9 * * *'  # This is UTC time, so it corresponds to 9:30 AM IST (Indian Standard Time)
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have your dependencies listed in requirements.txt

    - name: Run the script
      run: python ./tracker_aut.py # Replace with the actual path to your script
