name: Daily Script Runner

on:
  schedule:
    - cron: '30 4 * * *'  # This is UTC time (4:30 AM UTC is 9:30 AM IST)
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install ChromeDriver
      run: |
        python -m pip install chromedriver-binary
        # This ensures that the appropriate chromedriver is downloaded and set up in the PATH.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have your dependencies listed in requirements.txt

    - name: Verify Selenium Installation
      run: |
        python -m pip show selenium  # Verifies if selenium is installed

    - name: Run the script
      run: python ./tracker_aut.py  # Replace with the actual path to your script
